name: Generate Snake

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  push: # Executa ao fazer push na branch main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: keroldias123
          outputs: dist/snake.svg

      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
